### ISSUE TITLE
Entity Reference and Link implementations should be moved into the main module

### ISSUE THREAD

**Issue by laryn** [backdrop-contrib/textformatter#9]
They are no longer contrib.

**Comment by laryn** [comment]
I started on this but need to think through what an upgrade hook would need to do. @herbdool do you have any ideas or know of any similar updates in other modules?

I'd like to get this in and then make a new release.

**Comment by laryn** [comment]
I did a little searching and this may be one model to look at and see if the approach is relevant: https://github.com/backdrop-contrib/taxonomy_field_formatter/blob/1.x-1.x/taxonomy_field_formatter.install

**Comment by laryn** [comment]
@pgrayove-mcpl I did some testing on my own and since it was a broken implementation for these two in the previous release (and unlikely many people actually need the update functionality) I figured my testing on the update hook was enough. Of course, if you run into any issues with the forthcoming release please open an issue.

**Comment by herbdool** [comment]
I haven't tested but it looks ok.
